name: "jira-id-verifier"
descriprion: "this action checks the begining of the pull request title to contain a specific code like [TEST-123] at the beggining of the pull request title for tools like jira and more"
author: Mustafa Khan

outputs:
  output-results:
    description: "results of health check"
    value: ${{ steps.test.outputs.output-result }}
runs:
  using: "composite"
  steps:
    - name: test
      run: |
          sudo chmod u+x $GITHUB_ACTION_PATH/jira-verifier.sh
          $GITHUB_ACTION_PATH/jira-verifier.sh $(gh pr view --json title | cut -d ' ' -f 1 | sed 's/{"title":"//')
      shell: bash
